Middleware to proccess audio
iKonoTelecomunicaciones/menuflow pull request #91
Opened 2024-02-07 15:11 UTC by jcardenas3

2024-02-07 17:08 UTC, egalvis39 requested changes

2024-02-07 17:08 UTC, egalvis39 commented on menuflow/middlewares/asr.py
> +            form_data.add_field("audio", audio, filename="audio.ogg", content_type="audio/ogg")
Por si las dudas y algún día cambia sería mejor sacar el filename y el content_type del mensaje de matrix

2024-02-07 17:08 UTC, egalvis39 commented on menuflow/nodes/input.py
> +
Hacer la importación dentro del mismo if

2024-02-07 17:08 UTC, egalvis39 commented on menuflow/nodes/input.py
> +    middleware: "ASRMiddleware" = None
Este ya no esta aquí, en el constructor esta la propiedad middleware

2024-02-07 17:08 UTC, egalvis39 commented on menuflow/nodes/input.py
> +                MessageType.IMAGE,
Remover estos por ser redundantes con los if de arriba

2024-02-07 17:08 UTC, egalvis39 commented on menuflow/repository/flow.py
> +    middlewares: List[HTTPMiddleware | ASRMiddleware] = ib(default=[])
Eliminar está lista no se utiliza

2024-02-07 17:08 UTC, egalvis39 commented on menuflow/repository/flow_utils.py
> +    middlewares: List[HTTPMiddleware, IRMMiddleware] = ib(default=[])
No me elimine el de LLM

2024-02-07 17:08 UTC, egalvis39 commented on menuflow/repository/flow_utils.py
> +        elif middleware_type == Middlewares.asr:
El tipo en mayúsculas dentro del enum

2024-02-07 17:08 UTC, egalvis39 commented on menuflow/repository/middlewares/asr.py
> +          header1: "value1"
Ponga en los headers que hay que enviar el client token

2024-02-07 17:08 UTC, egalvis39 commented on menuflow/types.py
> +    asr = "asr"
Dentro de utils hay un types con los middlewares así que no es necesario este archivo

2024-02-07 17:08 UTC, egalvis39 commented on menuflow/utils/types.py
> +    asr = "asr"
Tipo en mayuscula

2024-02-08 22:53 UTC, egalvis39 approved these changes

2024-02-09 19:23 UTC, dbedoya approved these changes

2024-02-09 19:24 UTC, merged